// Auto-generated by scripts/generate-ukraine-map.mjs. Do not edit manually.

export interface BondCity {
  readonly id: string;
  readonly name: string;
  readonly lng: number;
  readonly lat: number;
  readonly x: number;
  readonly y: number;
}

export const BOND_CITIES: readonly BondCity[] = [
  { id: "UA-UAH-SHORT", name: "Kyiv", lng: 30.5234, lat: 50.4501, x: 472.1, y: 150.7 },
  { id: "UA-UAH-MID", name: "Lviv", lng: 24.0297, lat: 49.8397, x: 148.3, y: 198.2 },
  { id: "UA-USD-STD", name: "Odesa", lng: 30.7233, lat: 46.4825, x: 482.1, y: 449.3 },
  { id: "UA-EUR-STD", name: "Uzhhorod", lng: 22.2879, lat: 48.6208, x: 61.4, y: 291.3 },
  { id: "UA-UAH-WAR", name: "Kharkiv", lng: 36.2304, lat: 49.9935, x: 756.7, y: 186.3 },
  { id: "UA-USD-WAR", name: "Dnipro", lng: 35.0462, lat: 48.4647, x: 697.6, y: 303 },
];

export function getBondCity(id: string): BondCity | undefined {
  return BOND_CITIES.find((c) => c.id === id);
}
