// AUTO-GENERATED by .kamino-ref/gen-fixtures.js — do not edit by hand.
// Throwaway test payer pre-funded with 1,000 USDC on the fork via Anchor.toml
// [[test.validator.account]] injection (Variant B).
import { PublicKey } from "@solana/web3.js";
export const TEST_PAYER_USDC_ATA = new PublicKey("96mBCxzaYW4nwyXac5oLGV6m16aEmXbwWZ4XsTq4AJBT");
export const TEST_PAYER_USDC_BALANCE = 1_000_000_000n; // 1,000 USDC
